version: '2'
services:
  backend-service:
    image: booking-go-rest-api/backend-api-golang
    command: "./server"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/go/src/booking-go-rest-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000